### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by cool0707**
Bug fix for PR #241

### CODE REVIEW

**Comment by gjaekel** [comment]
Looks good for me at the first glance. I' going to apply the patch to my live systems to verify.

In a second step/commit: This deals with the Shared Mouse Pointer. One of the files is named `cursor.css`, the other `collab.js`. What's about to change this to `cursor.js` (and adjust `index.hml` for it)?

**Comment by cool0707** [comment]
I'm guessing that the file name is `collab.js` because @deleolajide reused the cursor sharing feature from together.js.
I also think it would be better to unify the name to `cursor.js` or `share_cursor.js` and change the css class name to `ofmeet-xxxx`.

**Comment by cool0707** [comment]
By the way, I know it's difficult, but I wish there was a feature to draw with a pen.

**Comment by gjaekel** [comment]
... which directly lead to a *usable* whiteboard feature. The former choosen "WBO" -- well, let say in a positive way -- have a HUGE of potential to enhance. Unfortunately (and *very* astonishing to me), this also holds for this particular component of CryptPad!

**Comment by cool0707** [comment]
I'm aware of the overlap in functionality with Whiteboard and CryptPad.
However, they don't work on my local network.

The difficult part in realizing this is the replication of drawing data.
Participants who join the room in the middle of a session need to be able to see the previous drawn data.
However, sending all the data every time it is updated is too much work, so we need to think of an appropriate sharing method.

**Comment by gjaekel** [comment]
> However, they don't work on my local network.

You really don't miss anything with this -- unfortunately. (For CryptPad, this subjects to the Whiteboard, only).

> The difficult part in realizing this is the replication of drawing data.
>Participants who join the room in the middle of a session need to be able to see the previous drawn data.

I see! And my spontaneous answer is: "So what! Just don't care about the middle-joining participants." :smile:

**Comment by deleolajide** [comment]
> However, sending all the data every time it is updated is too much work, so we need to think of an appropriate sharing method.

In the original version of Openfire Meetings, I used the [simple drawing application from togetherJS ](https://github.com/igniterealtime/pade/tree/master/apps/drawing) that used the data sharing features of XMPP MUC. When a new user joins, they receive all drawing history and only changes after that. The drawing data was JSON messages sent over XMPP presence stanzas.

**Comment by gjaekel** [comment]
Howto install this manually for a quick test, please?

**Comment by deleolajide** [comment]
> By the way, I know it's difficult, but I wish there was a feature to draw with a pen.

It should be straightforward to extend the shared cursor work you have done with the ability to draw.  As we can show a click with a red circle, we should be able to track cursor up/down and movement to draw any shape with a **shared pen**

The other approach is to take an existing whiteboard application like WBO and send the messages over XMPP and hosting the application in Openfire instead of a different container and different ports/server

**Comment by deleolajide** [comment]
> Howto install this manually for a quick test, please?

Openfire meeting has changed from the original version. I would have to revisit the code and re-work it

**Comment by gjaekel** [comment]
Do you have an old screenshot of this, actually?

**Comment by deleolajide** [comment]
image

**Comment by deleolajide** [comment]
image

Kaban board

**Comment by gjaekel** [comment]
Kanban board with a fixed Background image: **exactly** our need!

**Comment by deleolajide** [comment]
Lets see what we can do with the new collab.js code by @cool0707 
https://github.com/igniterealtime/pade/tree/master/apps/scrumblr

**Comment by gjaekel** [comment]
Maybe I'm annoying, but is this at least half the way to my Lounge, isn't it?
* I expect, there must be already a shared "pointer". 
* Instead of painting, some agent at the XMPP channel has to watch and calculate groupings of position. Then, it has to draw a big circle around and throw this participants to a breakout room.

**Comment by gjaekel** [comment]
I expect that the Collab group is made by all members of a XMPP room? And login and connection is handled by Pàdé? Or might this also be used in the context of an running OFmeet client?

**Comment by cool0707** [comment]
> In the original version of Openfire Meetings, I used the [simple drawing application from togetherJS ](https://github.com/igniterealtime/pade/tree/master/apps/drawing) that used the data sharing features of XMPP MUC. When a new user joins, they receive all drawing history and only changes after that. The drawing data was JSON messages sent over XMPP presence stanzas.

Thanks for the information.
I'll take a look when I have time.

**Pull request merged**
