### PR TITLE
Update custom_ofmeet.js

### PR DESCRIPTION
**Pull request by gjaekel**
the easter egg ...

image

### CODE REVIEW

**Comment by gjaekel** [comment]
@cool0707 Is there a special date timespan for 花見 ? Might use 🌸🍒💮

**Comment by cool0707** [comment]
花見 is done when the sakura (cherry blossoms) are in bloom, so the time of year varies depending on the year and latitude.
It usually takes about one to two weeks for the sakura to bloom and fall, and in Tokyo we usually do 花見 from the last week of March to the first week of April every year.
If you want to add one, I suggest you use 🌸.

**Comment by gjaekel** [comment]
I understand. Then, this is a much more floating date, even in comparison to the Easter event which is coupled with the period of Moon and shifting slightly year by year. 

So it's actually this days? And it's possible to celebrate regardless of the Corona situation?

May I couple the same date range as used for the Easter egg but switch it by the timezone UTC+9 (`getTimezoneOffset() == 9*60`)?

**Comment by cool0707** [comment]
In the case of the week, the calculation is complicated and not directly related to the blooming of sakura,
so I think it is better to fix it as March 25 to April 15.
This period will include the sakura blooming season in most parts of Japan.

**Comment by gjaekel** [comment]
image

**Pull request merged**
