### PR TITLE
Support configuration of Etherpad at AdminUI

### PR DESCRIPTION
**Pull request by gjaekel**
* Allow to configure the base-URL for external Etherpad and to enable this service at the AdminUI
* Pass the base-URL to the Jitsi Meet Webclient configuration (`.../config.js) if set and enabled.

### CODE REVIEW

**Comment by deleolajide** [comment]
@gjaekel Your version of ConfigServlet.java was old and overwrote my changes for WebAuthn. Git is supposed to stop that from happening. Could you please pull latest code from master into your branches or better still create a branch on igniterealtime as you now have permissions.

**Comment by gjaekel** [comment]
Sorry,  but I did a pull. It seems that I'm still untrained in using GitHub. Creating a feature branch on the main repository will save me to pull my fork all the times.

Do you restore the overwritten parts?

**Comment by gjaekel** [comment]
Should I also add the following suboption to the AdminUI ?
```
  // If etherpad integration is enabled, setting this to true will
    // automatically open the etherpad when a participant joins.  This
    // does not affect the mobile app since opening an etherpad
    // obscures the conference controls -- it's better to let users
    // choose to open the pad on their own in that case.
    // openSharedDocumentOnJoin: false,
```

**Comment by deleolajide** [comment]
> Do you restore the overwritten parts?

Yes. I did. It was just 2 lines, but thank God I noticed imediately otherwise, it would have cost a bit of time debugging later. I don't even use GIT commands and rely on Windows explorer and TortoiseGIT to get the job done. GIT is very good, but not perfect and stuff happens. catching it early is the key 👍 

image

**Comment by deleolajide** [comment]
>Should I also add the following suboption to the AdminUI ?

yes please if you can 👍

**Comment by gjaekel** [comment]
Before implementing I want to check out what's the effect of this actually is.

    Open Etherpad in any case, even for the first person, would be useless IMHO.
    Open it for a later joining participants if it's opened by others might make a bit more sense. But it's unlikely that it is implemented in such a way.

=> Maybe -- by help of command broadcast -- the "open" event should be propagated to the other participants if a Moderator open the document to direct attention to this. It might be a prepared meeting agenda, for instance.

**Comment by gjaekel** [comment]
OK, `config.openSharedDocumentOnJoin = true` opens the Etherpad panel on join for any person. IMHO, this will confuse most people because they have to close it via the menue to get the main video panel.

**Comment by deleolajide** [comment]
> IMHO, this will confuse most people because they have to close it via the menue to get the main video panel.

Maybe, but if the document is the minutes taken at every meeting, it does make sense for everyone to see the last minutes before a new meeting begins 👍 That is a valid use case for implementing it. Make the default setting false if you feel that strong about it.

**Comment by gjaekel** [comment]
Convinced :)

And independent from that, do you also see an easy technical way to hook the state and broadcast the visibility to all participants?

**Comment by deleolajide** [comment]
You could use boradcast message for that, but it would be easier to verbally ask participants to open the shared document manually themselves. Remote control of UI is generally frowned on

**Comment by gjaekel** [comment]
A few minutes before I got bad user feedback: It's stated that the Etherpad panel replaces by the tile view in the moment one speaker get the focus.

_Going to confirm this ..._

**Pull request merged**
