### PR TITLE
Fix breakout room

### PR DESCRIPTION
**Pull request by cool0707**
fix #298, #266 (only one part)

 - Changed breakout room to reflect the number of rooms immediately.
 - Room name can now be changed in the breakout room.
 - Breakout room now displays the remaining time/elapsed time.
 - Classified the code for the breakout room function.
 - Dialogs now looks similar to Jitsi Meet.
 - When the subject of Conference Captions is changed, `setSubject` function is now called.
 - Provisional support for the new UI of Jitsi Meet.

### CODE REVIEW

**Comment by gjaekel** [comment]
I did't take a look on, yet. From that, the following might be already implemented:
* Is it possible to "leave, but grey out" the out-breaked participants on the panel?
* For prospective enhancements: Do you see **technical** problems to use the breakout functionally by a non-moderator? It might be useful to (optionally) enable this for group meetings. Or to offer a function for a "quick private conference" between two (or a set of) arbitrary participants, e.g. a "(select and) double-click on a participants video window"

**Comment by cool0707** [comment]
> I did't take a look on, yet. From that, the following might be already implemented: Is it possible to "leave, but grey out" the out-breaked participants on the panel?

I' ve already implemented it.

> For prospective enhancements: Do you see **technical** problems to use the breakout functionally by a non-moderator? It might be useful to (optionally) enable this for group meetings. Or to offer a function for a "quick private conference" between two (or a set of) arbitrary participants, e.g. a "(select and) double-click on a participants video window"

If more than one person starts a breakout room at almost the same time, members may be transferred to a room they are not expecting.
I think we need to take some measures to prevent this from happening.
For example, during the 10-second waiting interval after someone starts a breakout room, others should not be able to start it.

**Comment by gjaekel** [comment]
> I' ve already implemented it.

:smiling_face_with_three_hearts:

I was asking about the technical view because I have the feature idea of this ad-hoc-breakout. From my experience with business meetings, even an ad-hoc private "Audio-Breakout" between two (or a selection) of persons would be a great enrichment.

**Comment by gjaekel** [comment]
@deleolajide What's the reason for the 10s waiting interval; is it just for user experience or is there any technical ? If this may be shortened, I would like to add our "vanilla configuration path"

**Comment by deleolajide** [comment]
> What's the reason for the 10s waiting interval; is it just for user experience or is there any technical ?

Can you please provide a reference. I can't find any setTimout with 10 secs delay in the code

**Comment by gjaekel** [comment]
Ups - maybe this is an older observation. I don't use breakout rooms very often but remember that there was a message with something like "you will send to another room within short time".

**Comment by cool0707** [comment]
> Can you please provide a reference. I can't find any setTimout with 10 secs delay in the code

10-second delay is set in these areas.
The previous code also had a 10-second delay, so I followed it.
(I changed it to show a countdown.)
https://github.com/igniterealtime/openfire-pade-plugin/blob/5de662d6b72efb2485e16587c4c29ab2acf009eb/src/webapp/custom_ofmeet.js#L2503
https://github.com/igniterealtime/openfire-pade-plugin/blob/5de662d6b72efb2485e16587c4c29ab2acf009eb/src/webapp/custom_ofmeet.js#L2769-L2787

**Comment by gjaekel** [comment]
Having a countdown is very good. In my eyes, 10s are a lot. I'll try user experience with 3-2-1 :)

By "accident", I found a technical restriction: At the moment, our user can't store the credentials because of a Windows Group Policy; they have to type-in it every time to enter a room. That's also holds for the breakout room, of corse. And during this time of login, the participants are "off control". If the moderator commands to finish a just started breakout to fast, the pullback will miss the participants.

I don't know if it's appropriate to monitor the pullback process, i.e. to check if the participants had received the message and will act to return.

**Pull request merged**
