### PR TITLE
Add custom confetti settings to Admin console

### PR DESCRIPTION
**Pull request by cool0707**
- Enable/Disable menu
- Close when menu is clicked or not
- Emoticon text type setting

### CODE REVIEW

**Comment by gjaekel** [comment]
Using the release V1.3.2, I got an exception on changing the set of emojis
```
20210301-090009.015 ERROR [Jetty-QTP-AdminConsole-1236] [o.j.u.JiveProperties] Incorrect string value: '\xF0\x9F\x91\x8F\xE2\x9D...' for column 'propValue' at row 1
java.sql.SQLException: Incorrect string value: '\xF0\x9F\x91\x8F\xE2\x9D...' for column 'propValue' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar:8.0.21]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.21.jar:8.0.21]
[...]
```

**Comment by cool0707** [comment]
I can't reproduce this in my environment, are you using MySQL as a database?
If you are using MySQL to set emoji, you need to set `character_set_server=utf8mb4` in my.ini to get such an error.
https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

**Comment by gjaekel** [comment]
Thank you for your hints. Yes, it's MySQL and from googeling around I came to the same conclusion. But until yet I don't get time to figure out if the database was initial set up with the wrong collation by us or if this is an issue caused by the SQL DDL scripts provided by OpenFire.

I think I have to dump, re-setup and import the whole database.

**Comment by gjaekel** [comment]
I'm still have to use MySQL 5.6. You can't set the innodb row format to dynamic in this version; in addition to use `utf8mb4`as charset and an appropriate collation, the dynamic row format must be set for each table.

I dump and re-import the whole database while filtering though `sed 's#CHARSET=utf8#CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC#g'` with success: The exception don't happen anymore.

**Pull request merged**
