### PR TITLE
Update JvbPluginWrapper.java

### LINKED ISSUE #88: Can't establish audio or video
Hello, once again.

I have created a video room on a Windows PC, with Chrome.  I am able to join the room with an iPad, running Safari.  However, no audio or video are transmitted.  The slashed mic and video icons are present in the self screen, even though I have selected to allow video and audio.  BEFORE the connection was established, audio and video were working.

image

Also, eventually, the iPad puts up a red message, saying "Unable to access camera.  Please check if another application is using this device, select another device from the settings menu or try to reload the application."  Options are to Dismiss or Contact support.  The latter option brings up a new tab, to about:blank

```
2020.11.17 15:50:39 INFO [IceUdpTransportManager connect thread]: org.jitsi.impl.neomedia.MediaStreamImpl - audio remote IP/port: 10.72.16.68/64230
2020.11.17 15:50:39 INFO [IceUdpTransportManager connect thread]: org.jitsi.videobridge.Channel - CAT=stat transport_connected,conf_id=2d64f4b0fd2f9d06,content=video,ch_id=930b725c69ad09dd,endp_id=7b116a5d,stream=845704130
2020.11.17 15:50:39 INFO [IceUdpTransportManager connect thread]: org.jitsi.impl.neomedia.MediaStreamImpl - video codec/freq: null/null Hz
2020.11.17 15:50:39 INFO [IceUdpTransportManager connect thread]: org.jitsi.impl.neomedia.MediaStreamImpl - video remote IP/port: 10.72.16.68/64230
2020.11.17 15:50:39 INFO [IceUdpTransportManager connect thread]: org.jitsi.videobridge.Channel - CAT=stat transport_connected,conf_id=2d64f4b0fd2f9d06,content=data,ch_id=889bcd963ac873e1,endp_id=7b116a5d
2020.11.17 15:50:39 ERROR [org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.connectThread]: org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer - Failed to accept a connection from a DTLS client!
java.io.IOException: org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl is closed!
at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.assertNotClosed(DatagramTransportImpl.java:124) ~[libjitsi-1.0-20190724.114721-390.jar:?]
at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.send(DatagramTransportImpl.java:477) ~[libjitsi-1.0-20190724.114721-390.jar:?]
at org.bouncycastle.crypto.tls.DTLSRecordLayer.sendRecord(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.bouncycastle.crypto.tls.DTLSRecordLayer.send(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.bouncycastle.crypto.tls.DTLSReliableHandshake$RecordLayerBuffer.sendToRecordLayer(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.bouncycastle.crypto.tls.DTLSReliableHandshake.writeHandshakeFragment(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.bouncycastle.crypto.tls.DTLSReliableHandshake.writeMessage(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.bouncycastle.crypto.tls.DTLSReliableHandshake.resendOutboundFlight(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.bouncycastle.crypto.tls.DTLSReliableHandshake.receiveMessage(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.bouncycastle.crypto.tls.DTLSServerProtocol.serverHandshake(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.bouncycastle.crypto.tls.DTLSServerProtocol.accept(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.runInConnectThread(DtlsPacketTransformer.java:1043) [libjitsi-1.0-20190724.114721-390.jar:?]
at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.access$000(DtlsPacketTransformer.java:40) [libjitsi-1.0-20190724.114721-390.jar:?]
at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer$1.run(DtlsPacketTransformer.java:1272) [libjitsi-1.0-20190724.114721-390.jar:?]
2020.11.17 15:50:39 INFO [org.jitsi.impl.neomedia.rtp.translator.OutputDataStreamImpl]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=1169163249 remainingRetries=9
2020.11.17 15:50:39 INFO [org.jitsi.impl.neomedia.RTPConnectorInputStream.receiveThread]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=9
2020.11.17 15:50:39 WARN [org.jitsi.impl.neomedia.RTPConnectorInputStream.receiveThread]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:39 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=8
2020.11.17 15:50:39 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:40 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=7
2020.11.17 15:50:40 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:40 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=6
2020.11.17 15:50:40 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:40 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=5
2020.11.17 15:50:40 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:40 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=4
2020.11.17 15:50:40 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:41 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=3
2020.11.17 15:50:41 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:41 INFO [ice4j.Agent-timer-pool-13-thread-2]: org.ice4j.ice.Agent - ICE state changed from Completed to Terminated. Local ufrag c5iv41enc30bng
2020.11.17 15:50:41 INFO [ice4j.Agent-timer-pool-13-thread-2]: org.jitsi.videobridge.IceUdpTransportManager - CAT=stat ice_state_change,conf_id=2d64f4b0fd2f9d06,content=data,ch_id=5594655c41a63790,endp_id=e9728ee9 old_state=Completed,new_state=Terminated
2020.11.17 15:50:41 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=2
2020.11.17 15:50:41 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:41 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=1
2020.11.17 15:50:41 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:42 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Sending a FIR to ssrc=2500364118 remainingRetries=0
2020.11.17 15:50:42 WARN [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-RTCPFeedbackMessageSender]: org.jitsi.impl.neomedia.rtp.translator.RTCPFeedbackMessageSender - Not sending an FIR because the stream RTP manager is null.
2020.11.17 15:50:42 INFO [ice4j.Agent-timer-pool-13-thread-2]: org.ice4j.ice.Agent - ICE state changed from Completed to Terminated. Local ufrag 5v8c11enc30bnm
2020.11.17 15:50:42 INFO [ice4j.Agent-timer-pool-13-thread-2]: org.jitsi.videobridge.IceUdpTransportManager - CAT=stat ice_state_change,conf_id=2d64f4b0fd2f9d06,content=data,ch_id=889bcd963ac873e1,endp_id=7b116a5d old_state=Completed,new_state=Terminated
2020.11.17 15:50:42 WARN [EndpointConnectionStatusMonitoring]: org.jitsi.videobridge.EndpointMessageTransport - SCTP connection with 7b116a5d not ready yet.
2020.11.17 15:50:42 WARN [EndpointConnectionStatusMonitoring]: org.jitsi.videobridge.EndpointMessageTransport - No available transport channel, can't send a message
2020.11.17 15:50:47 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-org.jitsi.videobridge.health.Health]: org.jitsi.videobridge.Videobridge - CAT=stat create_conf,conf_id=a36471d3cf647ba7 conf_name=null,logging=false,conf_count=4,ch_count=6,v_streams=4
2020.11.17 15:50:47 INFO [org.jitsi.utils.concurrent.RecurringRunnableExecutor.thread-org.jitsi.videobridge.health.Health]: org.jitsi.videobridge.health.Health - Performed a successful health check in 9ms. Sticky failure: false
```

Thanks again for all your help!

### PR DESCRIPTION
**Pull request by gjaekel**
* Use operations-system aware path separator for classpath
* Prepend path to configuration file location.

Hopefully fixes #88

### CODE REVIEW

**Comment by gjaekel** [comment]
The current build-fail isn't caused by my changes, right?
```
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ ofmeet ---

[INFO] Changes detected - recompiling the module!

[INFO] Compiling 1 source file to /home/travis/build/igniterealtime/openfire-pade-plugin/ofmeet/target/test-classes

[INFO] -------------------------------------------------------------

[ERROR] COMPILATION ERROR : 

[INFO] -------------------------------------------------------------

[ERROR] /home/travis/build/igniterealtime/openfire-pade-plugin/ofmeet/src/test/org/jivesoftware/openfire/plugin/ofmeet/BookmarkInterceptorTest.java:[21,17] package org.junit does not exist

[ERROR] /home/travis/build/igniterealtime/openfire-pade-plugin/ofmeet/src/test/org/jivesoftware/openfire/plugin/ofmeet/BookmarkInterceptorTest.java:[23,24] package org.junit does not exist

[ERROR] /home/travis/build/igniterealtime/openfire-pade-plugin/ofmeet/src/test/org/jivesoftware/openfire/plugin/ofmeet/BookmarkInterceptorTest.java:[23,1] static import only from classes and interfaces

[ERROR] /home/travis/build/igniterealtime/openfire-pade-plugin/ofmeet/src/test/org/jivesoftware/openfire/plugin/ofmeet/BookmarkInterceptorTest.java:[24,24] package org.junit does not exist

[ERROR] /home/travis/build/igniterealtime/openfire-pade-plugin/ofmeet/src/test/org/jivesoftware/openfire/plugin/ofmeet/BookmarkInterceptorTest.java:[24,1] static import only from classes and interfaces

[ERROR] /home/travis/build/igniterealtime/openfire-pade-plugin/ofmeet/src/test/org/jivesoftware/openfire/plugin/ofmeet/BookmarkInterceptorTest.java:[36,6] cannot find symbol

  symbol:   class Test

  location: class org.jivesoftware.openfire.plugin.ofmeet.BookmarkInterceptorTest

[ERROR] /home/travis/build/igniterealtime/openfire-pade-plugin/ofmeet/src/test/org/jivesoftware/openfire/plugin/ofmeet/BookmarkInterceptorTest.java:[62,6] cannot find symbol
```

**Comment by deleolajide** [comment]
>The current build-fail isn't caused by my changes, right?

No. I will fix travis later. It is building ok on my PC

**Comment by deleolajide** [comment]
Thanks for the PRs 👍

**Comment by gjaekel** [comment]
That's fine. Please give me a note if a new release is available to see if this will get OFMeet working, i.e. let the JVB user appear inside the new `ofmeet`room.

**Comment by deleolajide** [comment]
image

latest jars on my sever pade.chat. both users inside ofmeet room. It is not working yest because internal docker ports 8080/8443 are blocked and I am waiting for them to be opened and mapped to external proxy ports

**Pull request merged**
