### PR TITLE
Feature custom confetti

### PR DESCRIPTION
**Pull request by cool0707**
Enhanced the confetti feature based on @gjaekel's idea.

- Added a submenu to the confetti toolbox icon.
- Added custom confetti with emoji selected from the submenu.
- Changed the functions for creating toolbar icons in `custom_ofmeet.js` for submenus.
- Minified the SVG of some toolbar icons.
- The `create****Button()` function in `custom_ofmeet.js` has been consolidated into one place.
- Changed the confetti source code from minified to the original source code for better readability. (The size is not much different)
- Changed confetti to skip frames when processing is heavy.
- Made the confetti look a little more "festive".

### CODE REVIEW

**Comment by gjaekel** [comment]
As usual: A considerable contribution! As in the maxim of the boy scouts, in addition you did a lot of cleanup at every place you visit!

Because Eastern is coming up, for the release I would like to add a special default for the Easter week, in the same way as for XMas. We may use https://jsfiddle.net/9v2af1w5/ for the calculation of this moving date and throw some flowers and eggs. :smile:

**Comment by deleolajide** [comment]
Simply amazing @cool0707 This is the reactions feature everyone has been asking for 👍 🥇 

image

**Comment by gjaekel** [comment]
@deleolajide Thank you for sharing the screen shot to get a first impression! I'm busy with business things at the moment...
@cool0707 As written, my intention is not just to have "fun" here but also to use it as a feedback instrument for our "serious business case". You wrote, you don't like it. But I'll also want to have some pairs of positive/negative to support open voting.

A looking-ahead agreement would be to pull the concrete set of available items from the server.

**Comment by gjaekel** [comment]
> Made the confetti look a little more "festive".

Used lunch-break to take a look on my own.
* The popup should not close on click (but as already done on toolbar timeout ) to allow ot send more than one icon.
* For the moods, instead of the confetti rain, I thought to send just one per person and click, about something like
```
            if (text) {
                options = {
                    ...options,
                    particleCount: 1,
                    scalar: 10,
                    shapes: ['text:' + text]
                };
```
image

**Comment by cool0707** [comment]
> use it as a feedback instrument for our "serious business case".

In my opinion, if it is to be used in "serious business case", it would be better to add a vote button next to the Raise hand button or a sub-menu to the Raise hand button.

**Comment by gjaekel** [comment]
That's a very good and comprehensible idea -- A Hurrah! for discussing things...

An with your pre-work no big think to implement.

**Comment by cool0707** [comment]
Voting in Zoom, Teams, Google Meet, etc. has a question and choices for the moderator, and a dialog to enter whether it is anonymous or not, and when the voting starts, the participants are shown the answer dialog.
What @gjaekel is looking for is simpler, but I think it would be desirable to be able to implement both features in the future.

**Comment by gjaekel** [comment]
> What @gjaekel is looking for is simpler ...

Yes - And let me tell from experience that this **less** ***is*** **more**! It has to be used as simple as possible to be used or it won't. And there are a bunch of free online tools to prepare, execute and evaluate complex votings.

To my observations in one hand participants want to agree or disagree spontaneous to the current speaker, but in a "non-disturbing", silent way. That's was on my mind by the original idea of throwing "single positive/negative moods".

The second is, at the end of a somewhat longer statement, the speaker or some other ask the well-known phrase: Do you agree to me? Because this is spontaneous, also, there's no time to fill dialogs for 5-15s to "prepare" a vote.

Said that, there might be a combination of this: A feature-full "Prepare Voting" dialog with the instruments to prepare the (one or more?) question. But nevertheless, this may be used to invoke a anonymous/public voting by "one click"

**Pull request merged**
