### PR TITLE
Fixed initial letter avatars to be centered correctly.

### PR DESCRIPTION
**Pull request by cool0707**
The first letter avatar is now correctly centered.
Modified the position from a fixed value to a calculated value.

Added support for multi-byte spaces as separators.

### CODE REVIEW

**Comment by gjaekel** [comment]
Using a centered align is much better! Had have no appetite to figure this out. In addition, for a strange kind of reason, this code path was not passed for a long time.

**Comment by gjaekel** [comment]
There's a corresponding copy of the code inside the Pàdé webclient. I recently added the first-last-algorithm there.

_I'll going to figure out the corresponding patch/pull request_

**Comment by deleolajide** [comment]
> In the installation, it's the file `.../pade/classes/docs/inverse/index.js`. But I wasn't able to localize the source within _this_ repository, yet. Maybe it's located in another and pulled at the maven build ?!
> @deleolajide : May you give a hint?

https://github.com/igniterealtime/pade/blob/master/docs/inverse/index.js

**Comment by gjaekel** [comment]
@deleolajide : Thank you, will try to transfer it in an analogous way.

**Pull request merged**
