### PR TITLE
Fixed kick-related features

### PR DESCRIPTION
**Pull request by cool0707**
- Fixed "Ouch! You have been kicked out of the meet!" message to appear when kicked.
- Lobby screen now displays when rejoining a room after being kicked out of a lobby-enabled room.
- Remove affiliation when participants leave the room.

### CODE REVIEW

**Comment by gjaekel** [comment]
> Lobby screen now displays when rejoining a room after being kicked out of a lobby-enabled room.

:+1:

**Comment by deleolajide** [comment]
@cool0707 Unfortunatelty, I have re-organised the code to become a standard Openfire plugin. This means you will need to to re-fetch the latest code and re-apply the PR. I am very sorry for the inconvinience, [but it is required in order to build with GitHub Actions and auto-submit to Igniterealtime archiva](https://github.com/igniterealtime/openfire-pade-plugin/discussions/185).

Also, ofmeet already has a packet interceptor at https://github.com/igniterealtime/openfire-pade-plugin/blob/32dbb908c0c0ec03e08c6cd08b470c4262371cf6/src/java/org/jivesoftware/openfire/plugin/ofmeet/LobbyMuc.java#L160

Instead of a second interceptor class that will become confusing in the future, could you please merge your interceptor code at this point or re-write the LobbyMuc class if that works better for you 
https://github.com/igniterealtime/openfire-pade-plugin/blob/32dbb908c0c0ec03e08c6cd08b470c4262371cf6/src/java/org/jivesoftware/openfire/plugin/ofmeet/LobbyMuc.java#L235

**Comment by cool0707** [comment]
I've separated the classes because they affect kicks in rooms other than the lobby room, but I'll merge them into `LobbyMuc.java` if necessary.
I'm stumped on two-step verification for the GitHub Actions, so I'll re-PR when I get it resolved.

**Comment by deleolajide** [comment]
> I've separated the classes because they affect kicks in rooms other than the lobby room, but I'll merge them into `LobbyMuc.java` if necessary.

👍 You are absolutely correct. May be we should have moved the packet interceptor code in LobbyMuc to the seperate standalone class. I was trying to make sure all the interceptor code for ofmeet was all in the same place when debugging.

I suggest we do that next time we need update the packet interceptor.

**Pull request merged**
