### PR TITLE
Update custom_ofmeet.js

### PR DESCRIPTION
**Pull request by gjaekel**
Sort names in Contact Manager.

Support #50.

### CODE REVIEW

**Comment by deleolajide** [comment]
I had to fix syntax error from your PR with this commit - https://github.com/igniterealtime/openfire-pade-plugin/commit/1bcbae070c9083e5ffbe865b1a57005dd7f8be12
Please always confirm code works before submitting PR. It will help to spot when things break as early as possible

**Comment by gjaekel** [comment]
I kindly apologize! It was confirmed to work locally, but that's a copy'n'paste error as a result of using just the GitHub web client.

**Comment by deleolajide** [comment]
>I kindly apologize! 

No worries. I am sorry if I appear to criticize you as I make mistakes like that all the time.   I don't check code in detail as I assume you know what you are doing and the code was tested. Provided it solves a problem efficiently and does not break or compromise the overall application. I accept and merge any PR assuming it has been tested and works as explained.

A PR is mostly desired, but If you are using the web client to create the PR, then please paste the code into the issue instead and I can apply that and do the testing unless it is a simple one line or multiple lines that don't change existing logic.

**Comment by gjaekel** [comment]
I don't feel blamed, this was mostly self-critic. I was acting to fast, I missed to delete two lines while pasting in.

I know that you assume that I know what I'm doing; I feel honored by this. And therefore I do my best to double-check the pull request at the moment the diff is shown.

Is there any "lint for javascript" available at the GitHub CI to prevent such situations?

**Pull request merged**
