### PR TITLE
Add Hotkeys 

### PR DESCRIPTION
**Pull request by gjaekel**
Add hotkeys for
* C[o]ntacts Manager
* [B]reakout Rooms
* Shared [P]ointer

to support #299.

Thanks to the preliminary works, I thought this is very easy. But it don't work as expected, yet.

### CODE REVIEW

**Comment by deleolajide** [comment]
> But it don't work as expected, yet.

Is it working and fit for release?

**Comment by gjaekel** [comment]
I saw no reaction on hotkeys. But I stop working on that because of #292.

**Comment by gjaekel** [comment]
At hte Console, on pressing the assigned hotkeys, there are exceptions listed like
```
custom_ofmeet.js:853 Uncaught TypeError: Cannot read property 'stopPropagation' of undefined
    at Object.callback (custom_ofmeet.js:853)
    at Object.function (custom_ofmeet.js:1015)
    at window.onkeyup (app.bundle.min.js:93364)
```

**Comment by gjaekel** [comment]
If I disable the calls to `evt.stopPropagation()`, the hotkeys seems to work. What's the reason to put this call here, please?

But maybe a bit to good, because -- as it can be seen from the console log -- the Breakout Dialog may be called even if already open, because the hotkey still "fire"; the icon however can't be reached anymore.

**Pull request closed without merging**
