### PR TITLE
Update custom_ofmeet.js

### PR DESCRIPTION
**Pull request by gjaekel**
Even if scheme of (nick)name is "Lastname, Firstname", the avatar initials (used as default if no picture available) should be "FL".

This

### CODE REVIEW

**Comment by gjaekel** [comment]
Must be some other code location more: An inserted alert prove that the initials now are build in the intended way. But in the menu and placeholder an an emtpy video plane, it's still "wrong".

**Comment by deleolajide** [comment]
The correct location for the modified jitsi-meet source files is https://github.com/igniterealtime/openfire-pade-plugin/tree/master/web/src/main/webapp

Please it for any further modifications. The maven build script copied them into the classes folder after downloading and unzipping jitsi-meet from https://download.jitsi.org/jitsi-meet/src/

**Comment by deleolajide** [comment]
Also please accompany any PR with an issue like this - https://github.com/igniterealtime/openfire-pade-plugin/issues/18

It is needed for the change-log and also can be used in the workflow. 

Github  adds cross-references between issues and the commits from the PR. Also, the issue can be automatically closed by add the text **fix #nnn** (where nnn is the issue number) in the commit.

**Comment by deleolajide** [comment]
I have made this changes, but be advised that it only work with non-anonymous (authenticated) users who do not set an avatar in their vCards. For anonymous users, Jitsi-Meet's version will take priority and it does not recognize lastname, firstname  format

**Comment by gjaekel** [comment]
> I have made this changes, but be advised that it only work with non-anonymous (authenticated) users who do not set an avatar in their vCards. For anonymous users, Jitsi-Meet's version will take priority and it does not recognize lastname, firstname format

I completely understand. But on my Installation the provided patch shows no effect on the Avatar graphics. Using my account with the display name 'Jäkel, Guido', an inserted `alert(initital)` now gives `GJ`, but the pictures still show a circle with the letters `JG`.

**Pull request closed without merging**
