### PR TITLE
Update InProgressListServlet.java

### PR DESCRIPTION
**Pull request by gjaekel**
* rely on referrer
* add password state, conference size and member list to conference description. TODO: make this switchable
* pre-calculate display messages to minimize invasion and dependency from `app.bundle.min.js`

enhances #186

### CODE REVIEW

**Comment by gjaekel** [comment]
Introduce config switches to control the privacy level of published information
* `org.jitsi.videobridge.ofmeet.welcomepage.inprogresslist.enableSizeInfo` ::= show conference size
* `org.jitsi.videobridge.ofmeet.welcomepage.inprogresslist.enableProtectionInfo` ::= show lock symbol for protected rooms
* `org.jitsi.videobridge.ofmeet.welcomepage.inprogresslist.enableParticipantsInfo` ::= show participants account names

**Review by deleolajide — APPROVED** [review]
Agree with you that client JavaScript (app.bundle.min.js) is best place to format title, but this is the best to do it for easy maintenance of Jitsi code

**Comment by deleolajide** [comment]
Could you try updating the I18n file and the ofmeet-settings.jsp or ofmeet-uisettings.jsp next time you create configuration controls. Otherwise lets create a wiki page and document the the properties not accessible form admin web pages

**Comment by gjaekel** [comment]
> Could you try updating the I18n file and the ofmeet-settings.jsp or ofmeet-uisettings.jsp next time you create configuration controls.

Yes, I know it time to learn this.

**Pull request merged**
